#!/bin/sh
# fix_usb_serial.sh
# Diagnose and fix missing /dev/ttyUSB and /dev/serial on Debian cloud images.

set -e

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

log()  { printf '[INFO]  %s\n' "$*"; }
log_warn() { printf '[log_warn]  %s\n' "$*"; }
log_error()  { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)."
    fi
}

# ---------------------------------------------------------------------------
# Step 1 — Diagnose current state
# ---------------------------------------------------------------------------

diagnose() {
    log_info "=== Diagnostic Report ==="

    log_info "Kernel: $(uname -r)"

    log_info "Loaded USB serial modules:"
    lsmod | grep -E 'usbserial|cdc_acm|ftdi|cp210|ch34' || log_warn "None loaded."

    log_info "USB serial module files on disk:"
    find /lib/modules/"$(uname -r)" -name '*.ko*' \
        | grep -E 'ftdi|cp210|ch34|cdc_acm|usbserial' \
        || log_warn "None found — modules-extra may not be installed."

    log_info "USB devices visible to VM:"
    if command -v lsusb >/dev/null 2>&1; then
        lsusb || log_warn "lsusb returned no output."
    else
        log_warn "lsusb not available (install usbutils)."
    fi

    log_info "Existing serial device nodes:"
    ls /dev/ttyUSB* /dev/ttyACM* /dev/serial 2>/dev/null \
        || log_warn "No serial device nodes found."

    log_info "Relevant kernel messages (last 20):"
    dmesg | grep -iE 'usb|tty|serial' | tail -20 || log_warn "No relevant dmesg entries."

    log_info "=== End Diagnostic ==="
}

# ---------------------------------------------------------------------------
# Step 2 — Install required packages
# ---------------------------------------------------------------------------

install_packages() {
    log_info "Updating package lists..."
    apt-get update -qq

    log_info "Installing usbutils and kmod..."
    apt-get install -y usbutils kmod

    MODULES_PKG="linux-modules-extra-$(uname -r)"
    log_info "Checking for module files before installing extras..."

    FOUND=$(find /lib/modules/"$(uname -r)" -name '*.ko*' \
        | grep -E 'ftdi|cp210|ch34|cdc_acm|usbserial' | wc -l)

    if [ "$FOUND" -eq 0 ]; then
        log_info "USB serial modules not found. Installing ${MODULES_PKG}..."
        apt-get install -y "${MODULES_PKG}" || {
            log_warn "Could not install ${MODULES_PKG}."
            log_warn "You may need to switch from a cloud kernel to linux-image-amd64."
        }
    else
        log_info "Module files already present (${FOUND} found). Skipping extra modules install."
    fi
}

# ---------------------------------------------------------------------------
# Step 3 — Load modules
# ---------------------------------------------------------------------------

load_modules() {
    log_info "Loading USB serial kernel modules..."

    for mod in usbserial cdc_acm ftdi_sio cp210x ch341; do
        if modprobe "$mod" 2>/dev/null; then
            log_info "  Loaded: ${mod}"
        else
            log_warn "  Could not load: ${mod} (may not be needed for your hardware)"
        fi
    done
}

# ---------------------------------------------------------------------------
# Step 4 — Persist modules across reboots
# ---------------------------------------------------------------------------

persist_modules() {
    CONF="/etc/modules-load.d/usb-serial.conf"
    log_info "Writing persistent module config to ${CONF}..."

    tee "${CONF}" >/dev/null <<'EOF'
# USB serial modules — loaded at boot
# Generated by fix_usb_serial.sh
cdc_acm
ftdi_sio
cp210x
ch341
EOF

    log_info "Module persistence configured."
}

# ---------------------------------------------------------------------------
# Step 5 — Reload udev rules
# ---------------------------------------------------------------------------

reload_udev() {
    log_info "Reloading udev rules..."
    udevadm control --reload-rules
    udevadm trigger
    log_info "udev reloaded."
}

# ---------------------------------------------------------------------------
# Step 6 — dialout group
# ---------------------------------------------------------------------------

add_dialout() {
    # Only prompt if a non-root SUDO_USER is known
    TARGET_USER="${SUDO_USER:-}"

    if [ -z "$TARGET_USER" ]; then
        log_warn "Cannot determine non-root user. Add your user to 'dialout' manually:"
        log_warn "  sudo usermod -aG dialout <your_username>"
        return
    fi

    if id -nG "$TARGET_USER" | grep -qw dialout; then
        log_info "User '${TARGET_USER}' is already in the dialout group."
    else
        log_info "Adding '${TARGET_USER}' to the dialout group..."
        usermod -aG dialout "$TARGET_USER"
        log_info "Done. log_info out and back in for the group change to take effect."
    fi
}

# ---------------------------------------------------------------------------
# Step 7 — Final verification
# ---------------------------------------------------------------------------

verify() {
    log_info "=== Post-fix Verification ==="

    log_info "Loaded USB serial modules:"
    lsmod | grep -E 'usbserial|cdc_acm|ftdi|cp210|ch34' || log_warn "No modules loaded yet — may need reboot."

    log_info "Serial device nodes:"
    ls /dev/ttyUSB* /dev/ttyACM* /dev/serial 2>/dev/null \
        || log_warn "No device nodes found. Ensure USB passthrough is configured in your hypervisor."

    log_info "=== Done ==="
    log_info "If no devices appear, verify that your hypervisor is passing the USB device through to this VM."
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTION]

Options:
  --diagnose    Run diagnostic report only (no changes)
  --fix         Install packages, load modules, configure persistence
  --all         Diagnose, fix, and verify (default)
  --help        Show this help

Examples:
  sudo $(basename "$0") --diagnose
  sudo $(basename "$0") --fix
  sudo $(basename "$0") --all
EOF
}

main() {
    ACTION="${1:---all}"

    case "$ACTION" in
        --diagnose)
            diagnose
            ;;
        --fix)
            require_root
            install_packages
            load_modules
            persist_modules
            reload_udev
            add_dialout
            ;;
        --all)
            require_root
            diagnose
            install_packages
            load_modules
            persist_modules
            reload_udev
            add_dialout
            verify
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            log_warn "Unknown option: ${ACTION}"
            usage
            exit 1
            ;;
    esac
}

main "$@"
