########################### NETWORKS
networks:
  socketproxy:
    name: socketproxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/24
                

########################### Services     
services:
  ## Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  dockersocketproxy:
    container_name: ${CONTAINER_NAME_SOCKETPROXY:-socketproxy}
    image: ghcr.io/tecnativa/docker-socket-proxy:${IMAGE_TAG_SOCKETPROXY:-latest}
    restart: unless-stopped
    networks:
      - socketproxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "2375:2375"
    # - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network. When possible use this line.
    # I use the next line instead, as I need portainer to manage multiple docker endpoints within my home network.
    # - "2375:2375"
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Grant access=1; revoke=0
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # Portainer
      - INFO=1 # Portainer
      - NETWORKS=1 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 # Portainer
      - VOLUMES=1 # Portainer

  