########################### NETWORKS
networks:
  proxy:
    name: proxy
    external: true 

services:
  navidrome:
    image: "deluan/navidrome:${IMAGE_TAG:-latest}"
    container_name: "${CONTAINER_NAME:-navidrome}"
    user: ${DOCKER_PUID:?}:${DOCKER_PGID:?}
    # networks:
    #   - proxy
    ports:
      - "${HOST_IP:?}:4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 24h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      TZ: "${TZ}"
    volumes:
      - "${CONTAINER_VOLUME:-./volume_data}:/data"
      - "${NAVIDROME_MUSIC_FOLDER:?}:/music:ro"
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome.entrypoints=https-internal"
      - "traefik.http.routers.navidrome.entrypoints=https-external"
      - "traefik.http.routers.navidrome.rule=Host(`music.${DOMAIN_NAME:-local}`)"
      - "traefik.http.routers.navidrome.tls.certresolver=letsencrypt_dns"
      - "traefik.http.routers.navidrome.service=navidrome"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
      - homepage.group=Media Players
      - homepage.name=Navidrome
      - homepage.icon=navidrome.svg
      - homepage.href=https://music.${DOMAIN_NAME:?}
      - homepage.description=Music player
      - homepage.widget.type=navidrome
      - homepage.widget.url=https://music.${DOMAIN_NAME:?}
      - homepage.widget.user={{HOMEPAGE_FILE_NAVIDROME_USERNAME}}
      - homepage.widget.token={{HOMEPAGE_FILE_NAVIDROME_TOKEN}}
      - homepage.widget.salt={{HOMEPAGE_FILE_NAVIDROME_SALT}}
   