########################### STACK PROPERTIES
name: omada_controller

########################### SERVICES  
services:
  omada:
    image: mbentley/omada-controller:${IMAGE_TAG:-latest}
    container_name: omada
    restart: unless-stopped
    # user: ${PUID_DOCKER:?}:${PGID_DOCKER:?}       ## Overrides the user used to run the container process.
    ulimits:                                      ## Set resource limits
      nofile:                                     ## Maximum number of open file descriptors
        soft: 4096
        hard: 8192
    stop_grace_period: 60s                        ## Allow the DB time to stop
    network_mode: host                            ## Easier device discovery than bridge network
    environment:
      - PUID=${PUID_DOCKER:?}
      - PGID=${PGID_DOCKER:?}
      - MANAGE_HTTP_PORT=8088
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8088
      - PORTAL_HTTPS_PORT=8843
      - PORT_APP_DISCOVERY=27001
      # - PORT_ADOPT_V1=29812
      # - PORT_UPGRADE_V1=29813
      # - PORT_MANAGER_V1=29811
      - PORT_MANAGER_V2=29814
      - PORT_DISCOVERY=29810
      - PORT_TRANSFER_V2=29815
      - PORT_RTTY=29816
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
      # - SSL_CERT_NAME=tls.crt
      # - SSL_KEY_NAME=tls.key
      - TZ=Etc/UTC
      - TZ=${TZ:-Europe/Berlin}    
    volumes:
      - "${DOCKER_VOLUMES:?}/omada/data:/opt/tplink/EAPController/data" 
      - "${DOCKER_VOLUMES:?}/omada/logs:/opt/tplink/EAPController/logs" 

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.omada.entrypoints=https-internal"    ## "https-internal"; or "https-external"; or addtional traefik router/s needed for different config
      - "traefik.http.routers.omada.rule=Host(`omada.${DOMAIN_NAME:-home.arpa}`)"
      - "traefik.http.routers.omada.tls.certresolver=letsencrypt" ## letsencrypt; letsencrypt_dns; letsencrypt_testing
      - "traefik.http.routers.omada.service=omada"
      - "traefik.http.services.omada.loadbalancer.server.url=http://${HOST_IP:?}:8043"
      