mounts:
  # - name: data
  #   type: smb
  #   source: //smb_server_ip/data
  #   target: /mnt/data
  #   user_profile: profile1

  # - name: backups
  #   type: smb
  #   source: //smb_server_fqdn/backups
  #   target: /mnt/backups
  #   user_profile: profile1


  # - name: bootstrap
  #   type: nfs
  #   source: nfs_server_ip:/bootstrap
  #   target: /mnt/bootstrap

  # - name: data2
  #   type: nfs
  #   source: nfs_server_fqdn:/data2
  #   target: /mnt/data2